import Link from 'next/link';
import Head from 'next/head';

export default function About() {
  return (
    <>
    <Head><title>About — Turing Test | Social Intervention Group</title></Head>
    <div style={{
      minHeight: '100vh',
      background: 'linear-gradient(135deg, #1A2E4A 0%, #75AADB 50%, #F7F4EF 100%)',
      color: '#1A2E4A',
      fontFamily: 'Lora, "Times New Roman", serif'
    }}>
      {/* Header */}
      <header style={{
        padding: '20px 40px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        background: '#1A2E4A',
      }}>
        <Link
          href="/"
          aria-label="Turing Test – go to home page"
          style={{
            fontSize: '1.5rem',
            fontWeight: 700,
            fontFamily: 'Lora, "Times New Roman", serif',
            color: '#fff',
            textDecoration: 'none',
            borderRadius: 4,
            outline: 'none',
          }}
          onFocus={(e) => { e.currentTarget.style.outline = '3px solid #F7F4EF'; e.currentTarget.style.outlineOffset = '4px'; }}
          onBlur={(e) => { e.currentTarget.style.outline = 'none'; }}
        >
          Turing Test
        </Link>
        <Link href="/" style={{
          padding: '10px 24px',
          borderRadius: 999,
          background: '#F7F4EF',
          color: '#1A2E4A',
          color: '#fff',
          textDecoration: 'none',
          fontSize: '0.95rem',
          fontWeight: 600
        }}>
          Back to Home
        </Link>
      </header>

      {/* Main Content */}
      <main style={{
        maxWidth: 900,
        margin: '0 auto',
        padding: '80px 20px'
      }}>
        <div style={{
          background: 'rgba(255,255,255,0.7)',
          backdropFilter: 'blur(20px)',
          borderRadius: 20,
          border: '1px solid rgba(117,170,219,0.4)',
          padding: 48
        }}>
          <h1 style={{
            fontSize: '2.5rem',
            fontWeight: 700,
            marginBottom: 40,
              color: '#1A2E4A'
            }}>
              About This Project
          </h1>

          {/* Background */}
          <section style={{ marginBottom: 48 }}>
            <h2 style={{
              fontSize: '1.8rem',
              fontWeight: 600,
              marginBottom: 20,
              color: '#1A2E4A'
            }}>
              The Turing Test: A Brief History
            </h2>
            <p style={{
              fontSize: '1.1rem',
              lineHeight: 1.8,
              marginBottom: 16
            }}>
              In 1950, pioneering computer scientist <strong>Alan Turing</strong> proposed
              a test to determine whether a machine could exhibit intelligent behavior
              indistinguishable from a human. This became known as the <strong>Turing Test</strong>.
            </p>
            <p style={{
              fontSize: '1.1rem',
              lineHeight: 1.8
            }}>
              Today, as AI becomes more sophisticated, we're adapting this classic test
              to explore a critical question: Can people distinguish AI-generated responses
              from human responses in sensitive mental health contexts?
            </p>
          </section>

          {/* What is this? */}
          <section style={{ marginBottom: 48 }}>
            <h2 style={{
              fontSize: '1.8rem',
              fontWeight: 600,
              marginBottom: 20,
              color: '#1A2E4A'
            }}>
              What Is This Site?
            </h2>
            <p style={{
              fontSize: '1.1rem',
              lineHeight: 1.8,
              marginBottom: 16
            }}>
              This is an interactive research tool developed by the{' '}
              <strong>Social Intervention Group</strong> at{' '}
              <strong>Columbia School of Social Work</strong>. Our goal is to understand
              how people perceive and interact with AI in mental health contexts.
            </p>
            <p style={{
              fontSize: '1.1rem',
              lineHeight: 1.8
            }}>
              The game presents you with pairs of responses to mental health-related questions—one
              from a real Columbia student, one generated by AI. Your task is to identify which
              is which, helping us understand the nuances of human vs. AI communication in
              sensitive topics.
            </p>
          </section>

          {/* How it works */}
          <section style={{ marginBottom: 48 }}>
            <h2 style={{
              fontSize: '1.8rem',
              fontWeight: 600,
              marginBottom: 20,
              color: '#1A2E4A'
            }}>
              How Does It Work?
            </h2>
            <div style={{
              background: 'rgba(255,255,255,0.6)',
              borderRadius: 16,
              padding: 24,
              border: '1px solid rgba(117,170,219,0.3)'
            }}>
              <ol style={{
                fontSize: '1.1rem',
                lineHeight: 1.8,
                paddingLeft: 24
              }}>
                <li style={{ marginBottom: 12 }}>
                  <strong>Sign In</strong>: Authenticate with your Columbia email to begin
                </li>
                <li style={{ marginBottom: 12 }}>
                  <strong>Choose Your Experience</strong>: Select a mental health topic and
                  game mode (Swipe or Click)
                </li>
                <li style={{ marginBottom: 12 }}>
                  <strong>Make Your Guesses</strong>: Review responses and identify which
                  you think is human vs. AI
                </li>
                <li style={{ marginBottom: 12 }}>
                  <strong>See Results</strong>: After each round, discover the true sources
                  and your accuracy
                </li>
                <li>
                  <strong>Reflect</strong>: Consider what clues helped you distinguish
                  (or confused you!)
                </li>
              </ol>
            </div>
          </section>

          {/* What happens to data */}
          <section style={{ marginBottom: 48 }}>
            <h2 style={{
              fontSize: '1.8rem',
              fontWeight: 600,
              marginBottom: 20,
              color: '#1A2E4A'
            }}>
              What Happens to the Data?
            </h2>
            <p style={{
              fontSize: '1.1rem',
              lineHeight: 1.8,
              marginBottom: 16
            }}>
              Your gameplay data is collected for research purposes to help us understand:
            </p>
            <ul style={{
              fontSize: '1.1rem',
              lineHeight: 1.8,
              paddingLeft: 24,
              marginBottom: 16
            }}>
              <li>Patterns in how people identify AI vs. human content</li>
              <li>Which mental health topics are most challenging to distinguish</li>
              <li>The effectiveness of AI in replicating human empathy and nuance</li>
            </ul>
            <p style={{
              fontSize: '1.1rem',
              lineHeight: 1.8
            }}>
              All data is stored securely and used only for research. For complete details,
              please see our{' '}
              <Link href="/privacy" style={{
                color: '#75AADB',
                textDecoration: 'none',
                borderBottom: '1px solid rgba(117,170,219,0.5)'
              }}>
                Privacy page
              </Link>.
            </p>
          </section>

          {/* Who made this */}
          <section>
            <h2 style={{
              fontSize: '1.8rem',
              fontWeight: 600,
              marginBottom: 20,
              color: '#1A2E4A'
            }}>
              Who Made This?
            </h2>
            <p style={{
              fontSize: '1.1rem',
              lineHeight: 1.8,
              marginBottom: 16
            }}>
              This project is developed and maintained by:
            </p>
            <div style={{
              background: 'rgba(255,255,255,0.6)',
              borderRadius: 16,
              padding: 24,
              border: '1px solid rgba(117,170,219,0.3)',
              marginBottom: 16
            }}>
              <p style={{
                fontSize: '1.1rem',
                lineHeight: 1.8,
                marginBottom: 12
              }}>
                <strong>Principal Investigator</strong>: Elwin Wu, Professor at Columbia
                School of Social Work
              </p>
              <p style={{
                fontSize: '1.1rem',
                lineHeight: 1.8
              }}>
                <strong>Developer & Researcher</strong>: Zichen Zhao, Columbia Graduate School of
                Arts and Sciences
              </p>
            </div>
            <p style={{
              fontSize: '1.1rem',
              lineHeight: 1.8
            }}>
              Questions or feedback? Visit our{' '}
              <Link href="/contact" style={{
                color: '#75AADB',
                textDecoration: 'none',
                borderBottom: '1px solid rgba(117,170,219,0.5)'
              }}>
                Contact page
              </Link>.
            </p>
          </section>
        </div>
      </main>
    </div>
    </>
  );
}