import Link from 'next/link';

export default function About() {
  return (
    <div style={{
      maxWidth: 700,
      margin: '10vh auto',
      padding: '32px 24px',
      fontFamily: 'sans-serif',
      background: 'rgba(255,255,255,0.7)',
      backdropFilter: 'blur(20px)',
      borderRadius: 20,
      border: '1px solid rgba(139,115,85,0.3)',
      minHeight: '80vh'
    }}>
      <h1>About Us</h1>

      <p>
        The Turing Test Swipe App is a playful and thought-provoking experiment in human-AI interaction.
        It was designed to explore how well people can distinguish between responses written by real humans
        and those generated by large language models.
      </p>

      <p>
        This project was inspired by Alan Turing's foundational question: <i>“Can machines think?”</i> —
        and reimagined for today’s era of generative AI. With just a swipe, you’ll test your own intuition
        against cutting-edge machine responses.
      </p>

      <h2>Our Mission</h2>
      <ul>
        <li>Raise awareness about the power and limits of AI-generated text</li>
        <li>Foster critical thinking about what makes language feel human</li>
        <li>Build fun, interactive tools that make AI more accessible</li>
      </ul>

      <h2>Built by</h2>
      <p>
        This project was developed by <strong>Zichen Zhao</strong>, a data scientist and AI researcher passionate
        about ethical AI, mental health technology, and human-centered design.
      </p>

      <p>
        If you're curious about how this was built or want to contribute, visit the project on GitHub or reach out directly.
      </p>

      <Link href="/">
        <button style={{
          marginTop: 40,
          padding: '10px 20px',
          fontSize: '1rem',
          borderRadius: '8px',
          backgroundColor: '#333',
          color: 'white',
          border: 'none',
          cursor: 'pointer'
        }}>
          Home
        </button>
      </Link>
    </div>
  );
}